version: '3.1'

services:
    benchmark:
        build:
            context: .
            dockerfile: Dockerfile-openjdk
        image: ${DOCKER_USER}/openjdk-benchmark
        ports:
            - 8080:8080
        env_file:
            - ./.env
