services:
    openjdk:
        build:
            context: .
            dockerfile: Dockerfile-openjdk
        image: ${DOCKER_USER}/benchmark:openjdk-${IMAGE_TAG}
        ports:
            - ${OPENJDK_PORT}:8080
        env_file:
            - ./.env
    native:
        build:
            context: .
            dockerfile: Dockerfile-native
        image: ${DOCKER_USER}/benchmark:native-${IMAGE_TAG}
        ports:
            - ${NATIVE_PORT}:8080
        env_file:
            - ./.env
    native-ee:
       build:
           context: .
           dockerfile: Dockerfile-native-ee
       image: ${DOCKER_USER}/graalvm-ee:benchmark-native-ee-${IMAGE_TAG}
       ports:
           - ${NATIVE_EE_PORT}:8080
       env_file:
           - ./.env
    native-ee-pgo:
       build:
           context: .
           dockerfile: Dockerfile-native-ee-pgo
       image: ${DOCKER_USER}/graalvm-ee:benchmark-native-ee-pgo-${IMAGE_TAG}
       ports:
           - ${NATIVE_EE_PGO_PORT}:8080
       env_file:
           - ./.env
    graalvm:
        build:
            context: .
            dockerfile: Dockerfile-graalvm
        image: ${DOCKER_USER}/benchmark:graalvm-${IMAGE_TAG}
        ports:
            - ${GRAALVM_PORT}:8080
        env_file:
            - ./.env
    benchmark:
        build:
            context: .
            dockerfile: Dockerfile
        image: ${DOCKER_USER}/benchmark:runner-${IMAGE_TAG}
        volumes:
            - ./results:/results
        depends_on:
            - openjdk
            - native
            - graalvm
        env_file:
            - ./.env


