version: '3.1'

services:
    benchmark:
        build:
            context: .
            dockerfile: Dockerfile-native
        image: ${DOCKER_USER}/native-benchmark
        ports:
            - 8080:8080
        env_file:
            - ./.env
