version: 2

workflows:
  version: 2
  my-workflow:
    jobs:
      - build:
          context:
            - main
          filters:
            branches:
              only:
                - main
jobs:
  build:
    machine: true
    resource_class: dawg6/minipc
    steps:
      - checkout
      - run:
          name: Setup Env
          command: |
            echo 'export TAG=0.2.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
      - run:
          name: Build and push Docker images to public repo
          command: |
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker build . --network="host" -t $DOCKER_LOGIN/benchmark:runner-$TAG -t $DOCKER_LOGIN/benchmark:runner-latest -f Dockerfile
            docker build . --network="host" -t $DOCKER_LOGIN/benchmark:openjdk-$TAG -t $DOCKER_LOGIN/benchmark:openjdk-latest -f Dockerfile-openjdk
            docker build . --network="host" -t $DOCKER_LOGIN/benchmark:bellsoft-$TAG -t $DOCKER_LOGIN/benchmark:bellsoft-latest -f Dockerfile-bellsoft
            docker build . --network="host" -t $DOCKER_LOGIN/benchmark:graalvm-$TAG -t $DOCKER_LOGIN/benchmark:graalvm-latest -f Dockerfile-graalvm
            docker build . --network="host" -t $DOCKER_LOGIN/benchmark:native-$TAG -t $DOCKER_LOGIN/benchmark:native-latest -f Dockerfile-native
            docker push $DOCKER_LOGIN/benchmark:runner-$TAG
            docker push $DOCKER_LOGIN/benchmark:openjdk-$TAG
            docker push $DOCKER_LOGIN/benchmark:bellsoft-$TAG
            docker push $DOCKER_LOGIN/benchmark:graalvm-$TAG
            docker push $DOCKER_LOGIN/benchmark:native-$TAG
            docker push $DOCKER_LOGIN/benchmark:runner-latest
            docker push $DOCKER_LOGIN/benchmark:openjdk-latest
            docker push $DOCKER_LOGIN/benchmark:bellsoft-latest
            docker push $DOCKER_LOGIN/benchmark:graalvm-latest
            docker push $DOCKER_LOGIN/benchmark:native-latest


