version: 2

workflows:
  version: 2
  my-workflow:
    jobs:
      - build:
          context:
            - dawg6-main

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Setup Env
          command: |
            echo 'export TAG=0.2.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
      - run:
          name: Build and push Docker images
          command: |
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker build . -t dawg6/benchmark:runner-$TAG dawg6/benchmark:runner-latest -f Dockerfile
            docker build . -t dawg6/benchmark:openjdk-$TAG dawg6/benchmark:openjdk-latest -f Dockerfile
            docker build . -t dawg6/benchmark:graalvm-$TAG dawg6/benchmark:graalvm-latest -f Dockerfile
            docker build . -t dawg6/benchmark:native-$TAG dawg6/benchmark:native-latest -f Dockerfile
            docker push -a
