version: 2

workflows:
  version: 2
  my-workflow:
    jobs:
      - build:
          context:
            - main

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Setup Env
          command: |
            echo 'export TAG=0.2.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
      - run:
          name: Build and push Docker images
          command: |
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker build . -t $DOCKER_LOGIN/benchmark:runner-$TAG -t $DOCKER_LOGIN/benchmark:runner-latest -f Dockerfile
            docker build . -t $DOCKER_LOGIN/benchmark:openjdk-$TAG -t $DOCKER_LOGIN/benchmark:openjdk-latest -f Dockerfile-openjdk
            docker build . -t $DOCKER_LOGIN/benchmark:graalvm-$TAG -t $DOCKER_LOGIN/benchmark:graalvm-latest -f Dockerfile-graalvm
            docker build . -t $DOCKER_LOGIN/benchmark:native-$TAG -t $DOCKER_LOGIN/benchmark:native-latest -f Dockerfile-native
            docker push $DOCKER_LOGIN/benchmark:runner-$TAG
            docker push $DOCKER_LOGIN/benchmark:openjdk-$TAG
            docker push $DOCKER_LOGIN/benchmark:graalvm-$TAG
            docker push $DOCKER_LOGIN/benchmark:native-$TAG
            docker push $DOCKER_LOGIN/benchmark:runner-latest
            docker push $DOCKER_LOGIN/benchmark:openjdk-latest
            docker push $DOCKER_LOGIN/benchmark:graalvm-latest
            docker push $DOCKER_LOGIN/benchmark:native-latest
      - run:
          name: Build Docker images using Oracle GraalVM EE base images
          command: |
            echo $ORACLE_PWD | docker login -u $ORACLE_PWD --password-stdin container-registry.oracle.com
            docker build . -t $DOCKER_LOGIN/graalvm-ee:benchmark-native-ee-$TAG -t $DOCKER_LOGIN/graalvm-ee:benchmark-native-ee-latest -f Dockerfile-native-ee
            docker build . -t $DOCKER_LOGIN/graalvm-ee:benchmark-native-ee-gpo-$TAG -t $DOCKER_LOGIN/graalvm-ee:benchmark-native-ee-gpo-latest -f Dockerfile-native-ee-pgo
      - run:
          name: Push GraalVM EE Docker images
          command: |
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push $DOCKER_LOGIN/graalvm-ee:native-ee-$TAG
            docker push $DOCKER_LOGIN/graalvm-ee:native-ee-pgo-$TAG
            docker push $DOCKER_LOGIN/graalvm-ee:native-ee-latest
            docker push $DOCKER_LOGIN/graalvm-ee:native-ee-pgo-latest


